name: pre-commit

on:
  pull_request:
  push:
    branches: [tag-v1.5.22-bm]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    # don't run this on the tag-v1.5.22-bm branch
    if: github.ref != 'refs/heads/tag-v1.5.22-bm'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev
      - uses: pre-commit/action@v3.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
