name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - tag-v1.5.22-bm

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      packages: write
      contents: write
    with:
      forRef: v1.5.22-bm
